"""Tier-1 structured parsing of the Velop ``sysinfo.cgi`` dump.

``raw_text`` (stored verbatim in ``velop.sysinfo``) stays the source of truth.
This module pulls a handful of tabular / JSON sections out of that dump into
plain ``list[dict]`` records that ``store.py`` then writes to snapshot-linked
tables (``velop.device`` / ``wlan_client`` / ``backhaul`` / ``node``).

Every function here is *defensive*: the dump is generated by an embedded CGI
and is full of quirks (truncated names ending ``..``, mojibake such as
``Celetonâ€™s``, ditto-quote continuation rows for multi-MAC devices, an ``MCS``
column that is sometimes ``RSN`` rather than numeric, and table columns whose
values occasionally overflow their fixed width). A malformed line is skipped
rather than raised on, so a single bad row never loses a whole snapshot.
"""

from __future__ import annotations

import json
import re
from typing import Optional


def _clean(value: str) -> Optional[str]:
    """Strip a field; return ``None`` for an empty/whitespace-only value."""
    value = value.strip()
    return value or None


# --------------------------------------------------------------------------
# Generic section / fixed-width helpers
# --------------------------------------------------------------------------

# A separator line is the row of dashes (and spaces) under a table header,
# e.g. ``------  ----  ----------``. Its dash runs define the column widths.
_SEPARATOR_RE = re.compile(r"^[ \t]*-{3,}(?:[ \t]+-{3,})*[ \t]*$")


def _is_separator(line: str) -> bool:
    return bool(_SEPARATOR_RE.match(line))


def _column_spans(separator: str) -> list[tuple[int, Optional[int]]]:
    """Column boundaries from a dash separator line.

    Each span runs from the start of one dash run to the start of the next, so
    a value that overflows its own dash run (common in this dump) is still
    captured up to where the following column begins. The final span is
    open-ended (to end of line).
    """
    starts = [m.start() for m in re.finditer(r"-{3,}", separator)]
    spans: list[tuple[int, Optional[int]]] = []
    for i, start in enumerate(starts):
        end = starts[i + 1] if i + 1 < len(starts) else None
        spans.append((start, end))
    return spans


def _slice_fixed(line: str, spans: list[tuple[int, Optional[int]]]) -> list[Optional[str]]:
    return [_clean(line[start:end]) for start, end in spans]


def _section_rows(text: str, header_marker: str, row_re: re.Pattern) -> list[str]:
    """Return the raw data lines of a dash-delimited table.

    ``header_marker`` is matched against a line's stripped content (e.g.
    ``show_devices:``) -- exact, so the canonical section at the end of the
    dump wins over earlier ``----- wlan_report section -----`` style headers
    that share the word. The column-header line and the dash separator that
    follow it are skipped. Data lines are collected until the first line that
    is not a data row -- recognised by ``row_re``. A blank line ends the table,
    but so does the next section's header even when (as between ``bh_report``
    and ``wlan_report``) no blank line separates them.
    """
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == header_marker:
            # Find the separator that follows (within a few lines, past the
            # column-header row) and start collecting after it.
            for j in range(i + 1, min(i + 5, len(lines))):
                if _is_separator(lines[j]):
                    rows: list[str] = []
                    for row in lines[j + 1:]:
                        if not row.strip() or not row_re.match(row):
                            break
                        rows.append(row)
                    return rows
    return []


def _separator_for(text: str, header_marker: str) -> Optional[str]:
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == header_marker:
            for j in range(i + 1, min(i + 5, len(lines))):
                if _is_separator(lines[j]):
                    return lines[j]
    return None


# --------------------------------------------------------------------------
# show_devices -> velop.device
# --------------------------------------------------------------------------

# A ditto continuation row repeats the UUID column as quote marks and carries
# only an additional MAC (and its status) for the device on the line above.
_DITTO_RE = re.compile(r'^\s*"')

# Each table's data rows start with a recognisable first column, used to bound
# the section (the dump does not always separate tables with a blank line).
_DEVICE_ROW_RE = re.compile(r'^(?:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-|\s*")')
_WLAN_ROW_RE = re.compile(r"^[0-9a-fA-F]{2}(?::[0-9a-fA-F]{2}){5}\b")
_BACKHAUL_ROW_RE = re.compile(r"^[0-9A-Fa-f]{12}\b")


def parse_devices(text: str) -> list[dict]:
    """Parse the ``show_devices`` table into one record per device.

    Columns: UUID, MAC(s), IP, Conn., Stat, Name, FW Ver, Role. Continuation
    rows whose UUID column is ditto marks (``"   "   "``) append their extra
    MAC to the preceding device's ``extra_macs`` list rather than producing a
    record of their own.
    """
    separator = _separator_for(text, "show_devices:")
    if separator is None:
        return []
    spans = _column_spans(separator)

    devices: list[dict] = []
    for row in _section_rows(text, "show_devices:", _DEVICE_ROW_RE):
        if _DITTO_RE.match(row):
            if devices:
                _, mac, _ip, _conn, status, *_ = _slice_fixed(row, spans)
                if mac:
                    devices[-1]["extra_macs"].append(mac)
            continue

        fields = _slice_fixed(row, spans)
        if len(fields) < 8 or not fields[0]:
            continue
        uuid, mac, ip, conn, status, name, fw_ver, role = fields[:8]
        devices.append(
            {
                "uuid": uuid,
                "mac": mac,
                "ip": ip,
                "conn": conn,
                "status": status,
                "name": name,
                "fw_ver": fw_ver,
                "role": role,
                "extra_macs": [],
            }
        )
    return devices


# --------------------------------------------------------------------------
# JNAP GetDevices3 -> friendly_name enrichment for velop.device
# --------------------------------------------------------------------------


def friendly_name_index(jnap_payload: dict) -> dict[str, str]:
    """Index untruncated ``friendlyName`` by lowercased deviceID and by MAC.

    Built from a JNAP ``GetDevices3`` response (see ``fetch.fetch_jnap_devices``)
    so device records parsed from the CGI dump -- whose ``Name`` column the
    router truncates to ~16 chars and often leaves blank -- can be joined to the
    full name. UUID is the primary key (the CGI ``UUID`` matches JNAP
    ``deviceID`` case-insensitively); MAC keys are a fallback. Defensive: a
    payload without the expected shape just yields an empty index.
    """
    index: dict[str, str] = {}
    devices = (jnap_payload or {}).get("output", {}).get("devices", [])
    for dev in devices:
        if not isinstance(dev, dict):
            continue
        name = _clean(dev.get("friendlyName") or "")
        if not name:
            continue
        device_id = dev.get("deviceID")
        if device_id:
            index.setdefault(device_id.lower(), name)
        for iface in dev.get("knownInterfaces", []) or []:
            mac = iface.get("macAddress") if isinstance(iface, dict) else None
            if mac:
                index.setdefault(mac.upper(), name)
    return index


def enrich_friendly_names(devices: list[dict], index: dict[str, str]) -> list[dict]:
    """Set ``friendly_name`` on each device record from ``index``, in place.

    Matches on UUID first, then any of the device's MACs (primary + extras).
    The field is set to ``None`` when the device is absent from the JNAP data,
    so the column is always present. Returns ``devices`` for convenience.
    """
    for record in devices:
        name = None
        uuid = record.get("uuid")
        if uuid:
            name = index.get(uuid.lower())
        if name is None:
            for mac in [record.get("mac"), *(record.get("extra_macs") or [])]:
                if mac and mac.upper() in index:
                    name = index[mac.upper()]
                    break
        record["friendly_name"] = name
    return devices


# --------------------------------------------------------------------------
# wlan_report -> velop.wlan_client
# --------------------------------------------------------------------------


def parse_wlan_clients(text: str) -> list[dict]:
    """Parse the ``wlan_report`` table: Client, Stat, Net, Node, MCS, RSSI, When.

    Every field is a single whitespace-free token, so this splits on
    whitespace (more robust here than fixed width, since the ``Node`` value
    routinely overflows its narrow column). ``MCS`` is kept as text because it
    is sometimes ``RSN`` rather than a number; ``rssi`` is parsed to int.
    """
    clients: list[dict] = []
    for row in _section_rows(text, "wlan_report", _WLAN_ROW_RE):
        parts = row.split()
        if len(parts) < 7:
            continue
        client, stat, net, node, mcs, rssi, when = parts[:7]
        clients.append(
            {
                "client_mac": client,
                "stat": stat,
                "net": net,
                "node": node,
                "mcs": mcs,
                "rssi": _to_int(rssi),
                "last_seen": when,
            }
        )
    return clients


# --------------------------------------------------------------------------
# bh_report -> velop.backhaul
# --------------------------------------------------------------------------


def parse_backhaul(text: str) -> list[dict]:
    """Parse the ``bh_report`` table into one record per node.

    Columns: Node (MAC), NODE IP, PARENT IP, Intf., Chan., RSSI(AP/STA), Speed,
    State, Timestamp. Parsed fixed-width because the RSSI column is sometimes
    empty (a plain whitespace split could not tell which column went missing).
    """
    separator = _separator_for(text, "bh_report")
    if separator is None:
        return []
    spans = _column_spans(separator)

    rows: list[dict] = []
    for row in _section_rows(text, "bh_report", _BACKHAUL_ROW_RE):
        fields = _slice_fixed(row, spans)
        if len(fields) < 9 or not fields[0]:
            continue
        node_mac, node_ip, parent_ip, intf, chan, rssi, speed, state, ts = fields[:9]
        rows.append(
            {
                "node_mac": node_mac,
                "node_ip": node_ip,
                "parent_ip": parent_ip,
                "intf": intf,
                "chan": chan,
                "rssi": rssi,
                "speed": _to_float(speed),
                "state": state,
                "timestamp": _to_int(ts),
            }
        )
    return rows


# --------------------------------------------------------------------------
# DEVINFO JSON + show_devices -> velop.node
# --------------------------------------------------------------------------


def parse_devinfo(text: str) -> dict[str, dict]:
    """Parse the concatenated JSON blobs under ``cat /tmp/msg/DEVINFO/*``.

    Returns a mapping of node UUID -> the inner ``data`` object. Each blob is a
    top-level ``{...}`` object holding ``uuid`` and a nested ``data`` dict;
    blobs are split by brace-depth so the run of objects parses cleanly.
    """
    lines = text.splitlines()
    start = end = None
    for i, line in enumerate(lines):
        if line.strip() == "cat /tmp/msg/DEVINFO/*":
            start = i + 1
        elif start is not None and line.startswith("cat "):
            end = i
            break
    if start is None:
        return {}
    region = "\n".join(lines[start:end])

    info: dict[str, dict] = {}
    for blob in _json_objects(region):
        try:
            obj = json.loads(blob)
        except json.JSONDecodeError:
            continue
        uuid = obj.get("uuid")
        data = obj.get("data")
        if uuid and isinstance(data, dict):
            info[uuid] = data
    return info


def _json_objects(text: str) -> list[str]:
    """Split concatenated top-level JSON objects by brace depth (string-aware)."""
    objects: list[str] = []
    depth = 0
    start = None
    in_string = False
    escaped = False
    for i, ch in enumerate(text):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                objects.append(text[start:i + 1])
                start = None
    return objects


# Per-radio BSSID/channel keys promoted to top-level node columns; the full
# DEVINFO ``data`` dict is also kept verbatim for the OBJECT column.
_RADIO_KEYS = (
    "userAp2G_bssid",
    "userAp2G_channel",
    "userAp5GL_bssid",
    "userAp5GL_channel",
    "userAp5GH_bssid",
    "userAp5GH_channel",
)


def parse_nodes(text: str) -> list[dict]:
    """Combine ``show_devices`` node rows with their DEVINFO JSON.

    A "node" is a device whose role is ``master`` or ``slave``. Each record
    carries identity from ``show_devices`` plus SKU/serial/firmware/mode and
    per-radio BSSIDs/channels from DEVINFO, with the full DEVINFO ``data`` dict
    retained under ``devinfo`` for the CrateDB OBJECT column.
    """
    devinfo = parse_devinfo(text)
    nodes: list[dict] = []
    for dev in parse_devices(text):
        if dev["role"] not in ("master", "slave"):
            continue
        data = devinfo.get(dev["uuid"], {})
        node = {
            "uuid": dev["uuid"],
            "mac": dev["mac"],
            "ip": dev["ip"],
            "name": dev["name"],
            "role": dev["role"],
            "sku": data.get("SKU"),
            "serial_number": data.get("serialNumber"),
            "fw_ver": data.get("fw_ver") or dev["fw_ver"],
            "mode": data.get("mode"),
            "model_base": data.get("model_base"),
            "model_number": data.get("model_number"),
            "hw_version": data.get("hw_version"),
            "devinfo": data,
        }
        for key in _RADIO_KEYS:
            node[key.lower()] = _clean(data.get(key, "") or "")
        nodes.append(node)
    return nodes


# --------------------------------------------------------------------------
# Tier 7: ping statistics -> velop.ping
# --------------------------------------------------------------------------

# Section header: ``--- <target> ping statistics ---`` (target captured so a
# future change of probe host is recorded rather than assumed).
_PING_HEADER_RE = re.compile(r"^---\s+(?P<target>.+?)\s+ping statistics\s+---\s*$")
# ``2 packets transmitted, 2 packets received, 0% packet loss`` -- some ping
# builds drop the second "packets" and loss can be fractional.
_PING_COUNTS_RE = re.compile(
    r"(?P<tx>\d+)\s+packets transmitted,\s+(?P<rx>\d+)\s+(?:packets\s+)?received"
    r".*?(?P<loss>[\d.]+)%\s+packet loss"
)
# ``round-trip min/avg/max = 9.297/11.709/14.122 ms`` (also ``rtt`` builds with
# a trailing ``/mdev``); we keep min/avg/max.
_PING_RTT_RE = re.compile(
    r"(?:round-trip|rtt)\s+min/avg/max(?:/mdev)?\s*=\s*"
    r"(?P<min>[\d.]+)/(?P<avg>[\d.]+)/(?P<max>[\d.]+)"
)


def parse_ping(text: str) -> list[dict]:
    """Parse the WAN ping statistics block into a single-row record.

    Anchored on ``--- <target> ping statistics ---``; the following few lines
    carry the transmitted/received/loss counts and the round-trip min/avg/max.
    Any field that is absent (e.g. the RTT line is omitted on 100% loss) is
    left ``None`` rather than failing. Returns ``[]`` if the section is missing.
    """
    lines = text.splitlines()
    for i, line in enumerate(lines):
        header = _PING_HEADER_RE.match(line.strip())
        if not header:
            continue
        record = {
            "target": header.group("target"),
            "transmitted": None,
            "received": None,
            "loss_pct": None,
            "rtt_min": None,
            "rtt_avg": None,
            "rtt_max": None,
        }
        for follow in lines[i + 1:i + 5]:
            counts = _PING_COUNTS_RE.search(follow)
            if counts:
                record["transmitted"] = _to_int(counts.group("tx"))
                record["received"] = _to_int(counts.group("rx"))
                record["loss_pct"] = _to_float(counts.group("loss"))
            rtt = _PING_RTT_RE.search(follow)
            if rtt:
                record["rtt_min"] = _to_float(rtt.group("min"))
                record["rtt_avg"] = _to_float(rtt.group("avg"))
                record["rtt_max"] = _to_float(rtt.group("max"))
        return [record]
    return []


# --------------------------------------------------------------------------
# ip neigh (ARP/neighbour table) -> velop.ip_neighbor
# --------------------------------------------------------------------------

# A neighbour row: ``<ip> dev <iface> [lladdr <mac>] [router] [proxy ...] <STATE>``.
# The ``ip neigh:`` block mixes IPv4 and IPv6 (fe80::) entries; rows without a
# reachable MAC (e.g. ``... dev br0  FAILED``) omit the ``lladdr`` clause, and a
# neighbour that is itself a router carries a lowercase ``router`` flag before
# the uppercase state. State is occasionally absent, so it is optional.
_NEIGH_RE = re.compile(
    r"^(?P<ip>[0-9a-fA-F:.]+)\s+dev\s+(?P<iface>\S+)"
    r"(?:\s+lladdr\s+(?P<mac>[0-9a-fA-F]{2}(?::[0-9a-fA-F]{2})+))?"
    r"(?P<flags>(?:\s+[a-z_]+)*)"
    r"(?:\s+(?P<state>[A-Z][A-Z_]+))?\s*$"
)


def parse_ip_neighbors(text: str) -> list[dict]:
    """Parse the ``ip neigh:`` neighbour/ARP table: one row per IP.

    Each record carries the IP, its address family (``inet``/``inet6``), the
    bridge/interface it was seen on (``br0`` main LAN, ``br1`` guest, ``br2``
    IoT, ``eth0`` WAN), the resolved MAC (``None`` for an unresolved ``FAILED``
    entry), whether the neighbour advertised itself as a router, and the cache
    state (``REACHABLE``/``STALE``/``DELAY``/``FAILED``/...). This is the ARP
    cache at snapshot time -- a liveness signal and an IP<->MAC map independent
    of ``show_devices`` -- not a DHCP lease.
    """
    lines = text.splitlines()
    start = next((i + 1 for i, ln in enumerate(lines) if ln.strip() == "ip neigh:"), None)
    if start is None:
        return []

    rows: list[dict] = []
    for line in lines[start:]:
        if not line.strip():
            if rows:
                break
            continue  # skip the blank line between the header and the first row
        m = _NEIGH_RE.match(line)
        if not m:
            if rows:
                break
            continue
        ip = m.group("ip")
        flags = (m.group("flags") or "").split()
        rows.append(
            {
                "ip": ip,
                "family": "inet6" if ":" in ip else "inet",
                "iface": m.group("iface"),
                "mac": m.group("mac"),
                "is_router": "router" in flags,
                "state": m.group("state"),
            }
        )
    return rows


# ==========================================================================
# Shared helpers for the free-form Tier 5/6/9/10 sections
# ==========================================================================

# A titled dashed header, e.g. ``------------- ath0 Settings -------------``.
_DASH_TITLE_RE = re.compile(r"^-{5,}\s+.+\s+-{5,}\s*$")
# ``Key = value`` line (used by the apstats counters).
_KV_RE = re.compile(r"^(?P<key>\S.*?)\s*=\s*(?P<val>.+?)\s*$")


def _snake(label: str) -> str:
    """Lower-case a free-text label into a snake_case key."""
    return re.sub(r"[^\w]+", "_", label.strip().lower()).strip("_")


def _coerce(value: str):
    """Best-effort numeric coercion; non-numeric values (``<DISABLED>``) pass through."""
    value = value.strip()
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        return value


def _bounded_section(lines: list[str], start: int) -> int:
    """Index where the section opened at ``start`` ends.

    Stops at the next titled dashed header or ``====`` banner -- the dump's two
    ways of starting a new section.
    """
    for j in range(start, len(lines)):
        if _DASH_TITLE_RE.match(lines[j]) or lines[j].startswith("===="):
            return j
    return len(lines)


# --------------------------------------------------------------------------
# Tier 5: wifi apstats -> velop.radio_stats
# --------------------------------------------------------------------------

_APSTATS_HEADER_RE = re.compile(r"^-{5,}\s+wifi apstats section\s+-{5,}\s*$")
_RADIO_BAND_RE = re.compile(r"^radio level information of\s+(?P<band>.+?):\s*$")
_RADIO_NAME_RE = re.compile(r"^Radio Level Stats:\s+(?P<radio>\S+)")


def parse_radio_stats(text: str) -> list[dict]:
    """Parse the ``wifi apstats section`` into one record per radio.

    Each radio block opens with ``radio level information of <band>:`` then
    ``Radio Level Stats: <radio>``, followed by ``Label = value`` counters. All
    counters land in a ``stats`` OBJECT (snake_cased keys, numerics coerced);
    nested ``... per AC:`` / ``Co-located RNR stats:`` sub-counters are prefixed
    with their group so the duplicate AC labels don't collide.
    """
    lines = text.splitlines()
    start = next((i + 1 for i, ln in enumerate(lines) if _APSTATS_HEADER_RE.match(ln)), None)
    if start is None:
        return []
    end = _bounded_section(lines, start)

    radios: list[dict] = []
    current: Optional[dict] = None
    context: Optional[str] = None
    last_band: Optional[str] = None  # band appears one line before the radio name
    for line in lines[start:end]:
        band = _RADIO_BAND_RE.match(line)
        if band:
            last_band = band.group("band")
            current = None
            context = None
            continue
        name = _RADIO_NAME_RE.match(line)
        if name:
            current = {"radio": name.group("radio"), "band": last_band, "stats": {}}
            radios.append(current)
            context = None
            continue
        if current is None or not line.strip():
            continue
        stripped = line.strip()
        indented = line[0] in " \t"
        kv = _KV_RE.match(stripped)
        if kv:
            key = _snake(kv.group("key"))
            if indented and context:
                key = f"{context}_{key}"
            else:
                context = None
            current["stats"][key] = _coerce(kv.group("val"))
        elif not indented and stripped.endswith(":"):
            context = _snake(stripped[:-1])
        elif not indented:
            context = None
    return radios


def tag_radio_source(radios: list[dict], node: dict) -> list[dict]:
    """Stamp each radio record with the mesh node it was captured from, in place.

    ``radios`` are ``parse_radio_stats`` records; ``node`` is a ``parse_nodes``
    record (``mac``/``name``/``ip``/``role``). Radio names (``wifi0/1/2``) repeat
    across nodes and bands differ by model, so the source node is what makes a
    radio's identity unique across the mesh. Returns ``radios`` for convenience.
    """
    for radio in radios:
        radio["source_node_mac"] = node.get("mac")
        radio["source_node_name"] = node.get("name")
        radio["source_node_ip"] = node.get("ip")
        radio["source_role"] = node.get("role")
    return radios


# --------------------------------------------------------------------------
# Tier 6: athN Settings -> velop.radio_config
# --------------------------------------------------------------------------

_ATH_HEADER_RE = re.compile(r"^-{5,}\s+(?P<iface>ath\w+)\s+Settings\s+-{5,}\s*$")
# ``get_chwidth:0`` / ``g_disablecoext:0`` style setting tokens.
_SETTING_RE = re.compile(r"\b(?:get_|g_)(?P<key>\w+):(?P<val>\S+)")


def parse_radio_config(text: str) -> list[dict]:
    """Parse the per-VAP ``athN Settings`` blocks into one record per interface.

    Promotes ``interface``/``ssid``/``mac``/``frequency`` and collects every
    ``get_xxx:`` / ``g_xxx:`` token into a ``settings`` OBJECT. The embedded
    ``Current connected client(s)`` dump (client rows + per-client RSSI blocks)
    carries no setting tokens, so it is ignored naturally.
    """
    lines = text.splitlines()
    configs: list[dict] = []
    for i, line in enumerate(lines):
        header = _ATH_HEADER_RE.match(line)
        if not header:
            continue
        end = _bounded_section(lines, i + 1)
        record = {
            "interface": header.group("iface"),
            "ssid": None,
            "mac": None,
            "frequency": None,
            "settings": {},
        }
        for body in lines[i + 1:end]:
            if body.startswith("SSID:"):
                record["ssid"] = _clean(body.split(":", 1)[1])
            elif body.startswith("Mac address:"):
                record["mac"] = _clean(body.split(":", 1)[1])
            elif body.startswith("Frequency:"):
                record["frequency"] = _clean(body.split(":", 1)[1])
            for m in _SETTING_RE.finditer(body):
                record["settings"][m.group("key")] = _coerce(m.group("val"))
        configs.append(record)
    return configs


# --------------------------------------------------------------------------
# Tier 8: NIC Counters -> velop.nic_counter
# --------------------------------------------------------------------------

_NIC_RE = re.compile(
    r"^\s*(?P<intf>\S+)\s*:\s*RX bytes:(?P<rx>\d+).*?TX bytes:(?P<tx>\d+)"
)


def parse_nic_counters(text: str) -> list[dict]:
    """Parse the ``NIC Counters`` section: one row per interface.

    Each line is ``<intf> : RX bytes:<n> (..)  TX bytes:<n> (..)``; the raw
    byte counts are parsed (the human GiB suffix is derivable and dropped).
    """
    lines = text.splitlines()
    start = next((i + 1 for i, ln in enumerate(lines) if ln.strip() == "NIC Counters"), None)
    if start is None:
        return []

    rows: list[dict] = []
    for line in lines[start:]:
        if not line.strip():
            break
        m = _NIC_RE.match(line)
        if not m:
            break
        rows.append(
            {
                "intf": m.group("intf"),
                "rx_bytes": _to_int(m.group("rx")),
                "tx_bytes": _to_int(m.group("tx")),
            }
        )
    return rows


# --------------------------------------------------------------------------
# Tier 9: uptime / memory / cpu -> velop.system
# --------------------------------------------------------------------------

_UPTIME_RE = re.compile(
    r"\bup\s+(?:(?P<days>\d+)\s+days?,\s+)?"
    r"(?:(?P<hh>\d+):(?P<mm>\d+)|(?P<mins>\d+)\s+min)"
)
_LOADAVG_RE = re.compile(r"load average:\s+(?P<l1>[\d.]+),\s+(?P<l5>[\d.]+),\s+(?P<l15>[\d.]+)")
_MEM_RE = re.compile(
    r"^Mem:\s+(?P<total>\d+)\s+(?P<used>\d+)\s+(?P<free>\d+)\s+"
    r"(?P<shared>\d+)\s+(?P<buffers>\d+)\s+(?P<cached>\d+)"
)
_CPU_IDLE_RE = re.compile(r"^CPU:.*?(?P<idle>[\d.]+)%\s+idle")


def parse_system(text: str) -> list[dict]:
    """Parse scattered system-health fields into a single per-snapshot record.

    Pulls uptime + load average from the ``up ... load average:`` line, the
    ``Mem:`` row of the ``free`` table, and CPU idle from the ``CPU:`` line.
    Returns ``[]`` only if none of these are present.
    """
    record = {
        "uptime_secs": None,
        "load_1": None,
        "load_5": None,
        "load_15": None,
        "mem_total": None,
        "mem_used": None,
        "mem_free": None,
        "mem_shared": None,
        "mem_buffers": None,
        "mem_cached": None,
        "cpu_idle_pct": None,
    }
    found = False
    for line in text.splitlines():
        up = _UPTIME_RE.search(line)
        if up and record["uptime_secs"] is None:
            days = int(up.group("days") or 0)
            if up.group("mins") is not None:
                record["uptime_secs"] = days * 86400 + int(up.group("mins")) * 60
            else:
                record["uptime_secs"] = (
                    days * 86400 + int(up.group("hh")) * 3600 + int(up.group("mm")) * 60
                )
            found = True
        load = _LOADAVG_RE.search(line)
        if load and record["load_1"] is None:
            record["load_1"] = _to_float(load.group("l1"))
            record["load_5"] = _to_float(load.group("l5"))
            record["load_15"] = _to_float(load.group("l15"))
            found = True
        mem = _MEM_RE.match(line)
        if mem and record["mem_total"] is None:
            for key in ("total", "used", "free", "shared", "buffers", "cached"):
                record[f"mem_{key}"] = _to_int(mem.group(key))
            found = True
        cpu = _CPU_IDLE_RE.match(line)
        if cpu and record["cpu_idle_pct"] is None:
            record["cpu_idle_pct"] = _to_float(cpu.group("idle"))
            found = True
    return [record] if found else []


# --------------------------------------------------------------------------
# Tier 10: LLDP Information -> velop.lldp_neighbor
# --------------------------------------------------------------------------

_LLDP_HEADER_RE = re.compile(r"^=+\s+LLDP Information\s+=+\s*$")
_LLDP_IFACE_RE = re.compile(r"^Interface:\s+(?P<iface>[^,]+),.*?RID:\s+(?P<rid>\d+)")


def parse_lldp(text: str) -> list[dict]:
    """Parse the ``LLDP Information`` neighbour list: one row per neighbour.

    Each neighbour opens with an ``Interface:`` line and carries a ``Chassis:``
    block (ChassisID/SysName/SysDescr/MgmtIP + repeated ``Capability:`` lines)
    and a ``Port:`` block. ``mac `` prefixes on the IDs are stripped; the
    capabilities collapse into an OBJECT of name -> bool (``on``).
    """
    lines = text.splitlines()
    start = next((i + 1 for i, ln in enumerate(lines) if _LLDP_HEADER_RE.match(ln)), None)
    if start is None:
        return []
    end = next((j for j in range(start, len(lines)) if lines[j].startswith("====")), len(lines))

    neighbors: list[dict] = []
    current: Optional[dict] = None
    section = None  # 'chassis' or 'port' -- disambiguates the shared *ID lines
    for line in lines[start:end]:
        iface = _LLDP_IFACE_RE.match(line.strip())
        if iface:
            current = {
                "interface": _clean(iface.group("iface")),
                "rid": iface.group("rid"),
                "chassis_id": None,
                "sys_name": None,
                "sys_descr": None,
                "mgmt_ip": None,
                "port_id": None,
                "port_descr": None,
                "capabilities": {},
            }
            neighbors.append(current)
            section = None
            continue
        if current is None:
            continue
        stripped = line.strip()
        if stripped == "Chassis:":
            section = "chassis"
        elif stripped == "Port:":
            section = "port"
        elif stripped.startswith("ChassisID:"):
            current["chassis_id"] = _strip_mac(stripped.split(":", 1)[1])
        elif stripped.startswith("SysName:"):
            current["sys_name"] = _clean(stripped.split(":", 1)[1])
        elif stripped.startswith("SysDescr:"):
            current["sys_descr"] = _clean(stripped.split(":", 1)[1])
        elif stripped.startswith("MgmtIP:"):
            current["mgmt_ip"] = _clean(stripped.split(":", 1)[1])
        elif stripped.startswith("PortID:"):
            current["port_id"] = _strip_mac(stripped.split(":", 1)[1])
        elif stripped.startswith("PortDescr:"):
            current["port_descr"] = _clean(stripped.split(":", 1)[1])
        elif stripped.startswith("Capability:"):
            name, _, state = stripped.split(":", 1)[1].partition(",")
            name = _clean(name)
            if name:
                current["capabilities"][name] = state.strip().lower() == "on"
    return neighbors


def _strip_mac(value: str) -> Optional[str]:
    """Drop the ``mac `` prefix LLDP puts before chassis/port identifiers."""
    value = value.strip()
    if value.lower().startswith("mac "):
        value = value[4:].strip()
    return value or None


# --------------------------------------------------------------------------
# small numeric coercions
# --------------------------------------------------------------------------


def _to_int(value: Optional[str]) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(value.strip())
    except (ValueError, AttributeError):
        return None


def _to_float(value: Optional[str]) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value.strip())
    except (ValueError, AttributeError):
        return None
