"""Tier-1 structured parsing of the Velop ``sysinfo.cgi`` dump.

``raw_text`` (stored verbatim in ``velop.sysinfo``) stays the source of truth.
This module pulls a handful of tabular / JSON sections out of that dump into
plain ``list[dict]`` records that ``store.py`` then writes to snapshot-linked
tables (``velop.device`` / ``wlan_client`` / ``backhaul`` / ``node``).

Every function here is *defensive*: the dump is generated by an embedded CGI
and is full of quirks (truncated names ending ``..``, mojibake such as
``Celetonâ€™s``, ditto-quote continuation rows for multi-MAC devices, an ``MCS``
column that is sometimes ``RSN`` rather than numeric, and table columns whose
values occasionally overflow their fixed width). A malformed line is skipped
rather than raised on, so a single bad row never loses a whole snapshot.
"""

from __future__ import annotations

import json
import re
from typing import Optional


def _clean(value: str) -> Optional[str]:
    """Strip a field; return ``None`` for an empty/whitespace-only value."""
    value = value.strip()
    return value or None


# --------------------------------------------------------------------------
# Generic section / fixed-width helpers
# --------------------------------------------------------------------------

# A separator line is the row of dashes (and spaces) under a table header,
# e.g. ``------  ----  ----------``. Its dash runs define the column widths.
_SEPARATOR_RE = re.compile(r"^[ \t]*-{3,}(?:[ \t]+-{3,})*[ \t]*$")


def _is_separator(line: str) -> bool:
    return bool(_SEPARATOR_RE.match(line))


def _column_spans(separator: str) -> list[tuple[int, Optional[int]]]:
    """Column boundaries from a dash separator line.

    Each span runs from the start of one dash run to the start of the next, so
    a value that overflows its own dash run (common in this dump) is still
    captured up to where the following column begins. The final span is
    open-ended (to end of line).
    """
    starts = [m.start() for m in re.finditer(r"-{3,}", separator)]
    spans: list[tuple[int, Optional[int]]] = []
    for i, start in enumerate(starts):
        end = starts[i + 1] if i + 1 < len(starts) else None
        spans.append((start, end))
    return spans


def _slice_fixed(line: str, spans: list[tuple[int, Optional[int]]]) -> list[Optional[str]]:
    return [_clean(line[start:end]) for start, end in spans]


def _section_rows(text: str, header_marker: str, row_re: re.Pattern) -> list[str]:
    """Return the raw data lines of a dash-delimited table.

    ``header_marker`` is matched against a line's stripped content (e.g.
    ``show_devices:``) -- exact, so the canonical section at the end of the
    dump wins over earlier ``----- wlan_report section -----`` style headers
    that share the word. The column-header line and the dash separator that
    follow it are skipped. Data lines are collected until the first line that
    is not a data row -- recognised by ``row_re``. A blank line ends the table,
    but so does the next section's header even when (as between ``bh_report``
    and ``wlan_report``) no blank line separates them.
    """
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == header_marker:
            # Find the separator that follows (within a few lines, past the
            # column-header row) and start collecting after it.
            for j in range(i + 1, min(i + 5, len(lines))):
                if _is_separator(lines[j]):
                    rows: list[str] = []
                    for row in lines[j + 1:]:
                        if not row.strip() or not row_re.match(row):
                            break
                        rows.append(row)
                    return rows
    return []


def _separator_for(text: str, header_marker: str) -> Optional[str]:
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == header_marker:
            for j in range(i + 1, min(i + 5, len(lines))):
                if _is_separator(lines[j]):
                    return lines[j]
    return None


# --------------------------------------------------------------------------
# show_devices -> velop.device
# --------------------------------------------------------------------------

# A ditto continuation row repeats the UUID column as quote marks and carries
# only an additional MAC (and its status) for the device on the line above.
_DITTO_RE = re.compile(r'^\s*"')

# Each table's data rows start with a recognisable first column, used to bound
# the section (the dump does not always separate tables with a blank line).
_DEVICE_ROW_RE = re.compile(r'^(?:[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-|\s*")')
_WLAN_ROW_RE = re.compile(r"^[0-9a-fA-F]{2}(?::[0-9a-fA-F]{2}){5}\b")
_BACKHAUL_ROW_RE = re.compile(r"^[0-9A-Fa-f]{12}\b")


def parse_devices(text: str) -> list[dict]:
    """Parse the ``show_devices`` table into one record per device.

    Columns: UUID, MAC(s), IP, Conn., Stat, Name, FW Ver, Role. Continuation
    rows whose UUID column is ditto marks (``"   "   "``) append their extra
    MAC to the preceding device's ``extra_macs`` list rather than producing a
    record of their own.
    """
    separator = _separator_for(text, "show_devices:")
    if separator is None:
        return []
    spans = _column_spans(separator)

    devices: list[dict] = []
    for row in _section_rows(text, "show_devices:", _DEVICE_ROW_RE):
        if _DITTO_RE.match(row):
            if devices:
                _, mac, _ip, _conn, status, *_ = _slice_fixed(row, spans)
                if mac:
                    devices[-1]["extra_macs"].append(mac)
            continue

        fields = _slice_fixed(row, spans)
        if len(fields) < 8 or not fields[0]:
            continue
        uuid, mac, ip, conn, status, name, fw_ver, role = fields[:8]
        devices.append(
            {
                "uuid": uuid,
                "mac": mac,
                "ip": ip,
                "conn": conn,
                "status": status,
                "name": name,
                "fw_ver": fw_ver,
                "role": role,
                "extra_macs": [],
            }
        )
    return devices


# --------------------------------------------------------------------------
# wlan_report -> velop.wlan_client
# --------------------------------------------------------------------------


def parse_wlan_clients(text: str) -> list[dict]:
    """Parse the ``wlan_report`` table: Client, Stat, Net, Node, MCS, RSSI, When.

    Every field is a single whitespace-free token, so this splits on
    whitespace (more robust here than fixed width, since the ``Node`` value
    routinely overflows its narrow column). ``MCS`` is kept as text because it
    is sometimes ``RSN`` rather than a number; ``rssi`` is parsed to int.
    """
    clients: list[dict] = []
    for row in _section_rows(text, "wlan_report", _WLAN_ROW_RE):
        parts = row.split()
        if len(parts) < 7:
            continue
        client, stat, net, node, mcs, rssi, when = parts[:7]
        clients.append(
            {
                "client_mac": client,
                "stat": stat,
                "net": net,
                "node": node,
                "mcs": mcs,
                "rssi": _to_int(rssi),
                "last_seen": when,
            }
        )
    return clients


# --------------------------------------------------------------------------
# bh_report -> velop.backhaul
# --------------------------------------------------------------------------


def parse_backhaul(text: str) -> list[dict]:
    """Parse the ``bh_report`` table into one record per node.

    Columns: Node (MAC), NODE IP, PARENT IP, Intf., Chan., RSSI(AP/STA), Speed,
    State, Timestamp. Parsed fixed-width because the RSSI column is sometimes
    empty (a plain whitespace split could not tell which column went missing).
    """
    separator = _separator_for(text, "bh_report")
    if separator is None:
        return []
    spans = _column_spans(separator)

    rows: list[dict] = []
    for row in _section_rows(text, "bh_report", _BACKHAUL_ROW_RE):
        fields = _slice_fixed(row, spans)
        if len(fields) < 9 or not fields[0]:
            continue
        node_mac, node_ip, parent_ip, intf, chan, rssi, speed, state, ts = fields[:9]
        rows.append(
            {
                "node_mac": node_mac,
                "node_ip": node_ip,
                "parent_ip": parent_ip,
                "intf": intf,
                "chan": chan,
                "rssi": rssi,
                "speed": _to_float(speed),
                "state": state,
                "timestamp": _to_int(ts),
            }
        )
    return rows


# --------------------------------------------------------------------------
# DEVINFO JSON + show_devices -> velop.node
# --------------------------------------------------------------------------


def parse_devinfo(text: str) -> dict[str, dict]:
    """Parse the concatenated JSON blobs under ``cat /tmp/msg/DEVINFO/*``.

    Returns a mapping of node UUID -> the inner ``data`` object. Each blob is a
    top-level ``{...}`` object holding ``uuid`` and a nested ``data`` dict;
    blobs are split by brace-depth so the run of objects parses cleanly.
    """
    lines = text.splitlines()
    start = end = None
    for i, line in enumerate(lines):
        if line.strip() == "cat /tmp/msg/DEVINFO/*":
            start = i + 1
        elif start is not None and line.startswith("cat "):
            end = i
            break
    if start is None:
        return {}
    region = "\n".join(lines[start:end])

    info: dict[str, dict] = {}
    for blob in _json_objects(region):
        try:
            obj = json.loads(blob)
        except json.JSONDecodeError:
            continue
        uuid = obj.get("uuid")
        data = obj.get("data")
        if uuid and isinstance(data, dict):
            info[uuid] = data
    return info


def _json_objects(text: str) -> list[str]:
    """Split concatenated top-level JSON objects by brace depth (string-aware)."""
    objects: list[str] = []
    depth = 0
    start = None
    in_string = False
    escaped = False
    for i, ch in enumerate(text):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                objects.append(text[start:i + 1])
                start = None
    return objects


# Per-radio BSSID/channel keys promoted to top-level node columns; the full
# DEVINFO ``data`` dict is also kept verbatim for the OBJECT column.
_RADIO_KEYS = (
    "userAp2G_bssid",
    "userAp2G_channel",
    "userAp5GL_bssid",
    "userAp5GL_channel",
    "userAp5GH_bssid",
    "userAp5GH_channel",
)


def parse_nodes(text: str) -> list[dict]:
    """Combine ``show_devices`` node rows with their DEVINFO JSON.

    A "node" is a device whose role is ``master`` or ``slave``. Each record
    carries identity from ``show_devices`` plus SKU/serial/firmware/mode and
    per-radio BSSIDs/channels from DEVINFO, with the full DEVINFO ``data`` dict
    retained under ``devinfo`` for the CrateDB OBJECT column.
    """
    devinfo = parse_devinfo(text)
    nodes: list[dict] = []
    for dev in parse_devices(text):
        if dev["role"] not in ("master", "slave"):
            continue
        data = devinfo.get(dev["uuid"], {})
        node = {
            "uuid": dev["uuid"],
            "mac": dev["mac"],
            "ip": dev["ip"],
            "name": dev["name"],
            "role": dev["role"],
            "sku": data.get("SKU"),
            "serial_number": data.get("serialNumber"),
            "fw_ver": data.get("fw_ver") or dev["fw_ver"],
            "mode": data.get("mode"),
            "model_base": data.get("model_base"),
            "model_number": data.get("model_number"),
            "hw_version": data.get("hw_version"),
            "devinfo": data,
        }
        for key in _RADIO_KEYS:
            node[key.lower()] = _clean(data.get(key, "") or "")
        nodes.append(node)
    return nodes


# ==========================================================================
# Tiers 5-10 -- SCAFFOLD ONLY (not yet implemented)
# --------------------------------------------------------------------------
# Each stub below is anchored to its section in ``sampleoutput.txt`` and
# documents the intended record shape, so the later implementation pass only
# has to fill in the body. Like the Tier-1 parsers these return ``list[dict]``
# (single-row sections return a one-element list) so ``store_tier1``-style bulk
# insertion stays uniform. Until implemented they return ``[]`` -- callers and
# tests can already import and exercise them without raising. DDL and CLI
# wiring are deliberately deferred until each parser is real, so no empty
# tables get created in the meantime.
# ==========================================================================


def parse_radio_stats(text: str) -> list[dict]:
    """TODO(tier-5): parse the ``wifi apstats section``.

    Anchor: ``------------- wifi apstats section -------------`` (one block per
    radio, e.g. ``Radio Level Stats: wifi1`` for 2.4G). Body is ``Label = value``
    counter lines (``Tx Data Packets``, ``Rx Data Bytes``, ``Rx RSSI``,
    ``Tx failures`` ...), some with nested ``per AC`` sub-counters.
    Intended: one row per radio per snapshot, columns ``radio``/``band`` plus a
    snake_cased column (or an OBJECT blob) per counter.
    """
    return []  # not yet implemented


def parse_radio_config(text: str) -> list[dict]:
    """TODO(tier-6): parse the per-VAP ``athN Settings`` blocks.

    Anchor: ``------------- ath0 Settings -------------`` (ath0/1/2/3/10 ...).
    Each block mixes ``Key: value`` lines (``Interface name``, ``SSID``,
    ``Mac address``, ``Frequency``) with ``... get_xxx:N`` settings (chwidth,
    mode, shortgi, wmm, hide_ssid, bintval, dtim_period, protmode, wds).
    Intended: one row per VAP per snapshot keyed by ``interface``.
    """
    return []  # not yet implemented


def parse_ping(text: str) -> list[dict]:
    """TODO(tier-7): parse the WAN ping statistics.

    Anchor: ``--- www.linksys.com ping statistics ---``. Two lines:
    ``N packets transmitted, N packets received, P% packet loss`` and
    ``round-trip min/avg/max = a/b/c ms``.
    Intended: one row per snapshot -- ``target``, ``transmitted``, ``received``,
    ``loss_pct``, ``rtt_min``, ``rtt_avg``, ``rtt_max``.
    """
    return []  # not yet implemented


def parse_nic_counters(text: str) -> list[dict]:
    """TODO(tier-8): parse the ``NIC Counters`` section.

    Anchor: ``NIC Counters``. One line per interface, e.g.
    ``br0 : RX bytes:36301150454 (33.8 GiB)  TX bytes:166679092879 (155.2 GiB)``.
    Intended: one row per interface per snapshot -- ``intf``, ``rx_bytes``,
    ``tx_bytes`` (parse the raw byte counts; the human GiB suffix is derivable).
    """
    return []  # not yet implemented


def parse_system(text: str) -> list[dict]:
    """TODO(tier-9): parse overall system health.

    Sources are scattered near the top of the dump: ``UpTime:`` /
    ``load average:`` line, the ``Memory Use:`` ``free`` table (Mem total/used/
    free/shared/buffers/cached), and the ``CPU:`` usr/sys/idle line.
    Intended: one row per snapshot -- ``uptime_secs``, ``load_1``/``load_5``/
    ``load_15``, ``mem_total``/``mem_used``/``mem_free``, ``cpu_idle_pct`` ...
    """
    return []  # not yet implemented


def parse_lldp(text: str) -> list[dict]:
    """TODO(tier-10): parse the ``LLDP Information`` neighbour list.

    Anchor: ``========================== LLDP Information ==========================``.
    Neighbours are separated by dashed lines; each has ``Interface:`` plus a
    ``Chassis:`` block (``ChassisID``, ``SysName``, ``SysDescr``, ``MgmtIP``,
    repeated ``Capability:`` lines) and a ``Port:`` block (``PortID``,
    ``PortDescr``).
    Intended: one row per neighbour per snapshot -- ``interface``, ``chassis_id``,
    ``sys_name``, ``mgmt_ip``, ``port_id``, ``port_descr``, ``capabilities``.
    """
    return []  # not yet implemented


# --------------------------------------------------------------------------
# small numeric coercions
# --------------------------------------------------------------------------


def _to_int(value: Optional[str]) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(value.strip())
    except (ValueError, AttributeError):
        return None


def _to_float(value: Optional[str]) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value.strip())
    except (ValueError, AttributeError):
        return None
