"""Canonical CrateDB schema for the structured ``velop.*`` tables.

The watcher no longer writes to CrateDB directly. Records flow watcher -> Kafka
(Confluent-Avro) -> Kafka Connect JDBC sinks -> CrateDB, so the tables must
**pre-exist** (the sinks run ``auto.create=false``). This module is the single
source of truth for each table's column order and CrateDB type:

- ``kafka_sink.TABLE_SPECS`` mirrors :data:`TABLES` (asserted in tests), and
- ``sql/velop_schema.sql`` is generated by :func:`schema_sql` (run
  ``python -m velop_watcher.schema`` to regenerate it).

``id``/``snapshot_id``/``fetched_at`` are prepended to every table and are not
listed per-table here. Only the 11 structured tables live here; the raw_text
dumps (``sysinfo``/``node_sysinfo``) and the old ``oui`` cache are gone with the
direct-write path.
"""

from __future__ import annotations

# Columns prepended to every structured table, in order.
PK_PREFIX: tuple[tuple[str, str], ...] = (
    ("id", "TEXT PRIMARY KEY"),
    ("snapshot_id", "TEXT"),
    ("fetched_at", "TIMESTAMP WITH TIME ZONE"),
)

# Per-table data columns: ordered (name, CrateDB type). Order must match the
# Avro column order in kafka_sink.TABLE_SPECS (a test asserts this).
TABLES: dict[str, list[tuple[str, str]]] = {
    "device": [
        ("uuid", "TEXT"), ("mac", "TEXT"), ("mac_vendor", "TEXT"), ("ip", "TEXT"),
        ("conn", "TEXT"), ("status", "TEXT"), ("name", "TEXT"), ("friendly_name", "TEXT"),
        ("fw_ver", "TEXT"), ("role", "TEXT"),
        ("extra_macs", "ARRAY(TEXT)"), ("extra_macs_vendor", "ARRAY(TEXT)"),
    ],
    "wlan_client": [
        ("client_mac", "TEXT"), ("client_mac_vendor", "TEXT"), ("stat", "TEXT"),
        ("net", "TEXT"), ("node", "TEXT"), ("mcs", "TEXT"), ("rssi", "INTEGER"),
        ("last_seen", "TEXT"),
    ],
    "backhaul": [
        ("node_mac", "TEXT"), ("node_mac_vendor", "TEXT"), ("node_ip", "TEXT"),
        ("parent_ip", "TEXT"), ("intf", "TEXT"), ("chan", "TEXT"), ("rssi", "TEXT"),
        ("speed", "DOUBLE"), ("state", "TEXT"), ("timestamp", "BIGINT"),
    ],
    "ping": [
        ("target", "TEXT"), ("transmitted", "INTEGER"), ("received", "INTEGER"),
        ("loss_pct", "DOUBLE"), ("rtt_min", "DOUBLE"), ("rtt_avg", "DOUBLE"),
        ("rtt_max", "DOUBLE"),
    ],
    "node": [
        ("uuid", "TEXT"), ("mac", "TEXT"), ("mac_vendor", "TEXT"), ("ip", "TEXT"),
        ("name", "TEXT"), ("role", "TEXT"), ("sku", "TEXT"), ("serial_number", "TEXT"),
        ("fw_ver", "TEXT"), ("mode", "TEXT"), ("model_base", "TEXT"),
        ("model_number", "TEXT"), ("hw_version", "TEXT"),
        ("userap2g_bssid", "TEXT"), ("userap2g_bssid_vendor", "TEXT"), ("userap2g_channel", "TEXT"),
        ("userap5gl_bssid", "TEXT"), ("userap5gl_bssid_vendor", "TEXT"), ("userap5gl_channel", "TEXT"),
        ("userap5gh_bssid", "TEXT"), ("userap5gh_bssid_vendor", "TEXT"), ("userap5gh_channel", "TEXT"),
        ("devinfo", "OBJECT(IGNORED)"),
    ],
    "radio_stats": [
        ("radio", "TEXT"), ("band", "TEXT"), ("source_node_mac", "TEXT"),
        ("source_node_name", "TEXT"), ("source_node_ip", "TEXT"), ("source_role", "TEXT"),
        ("stats", "OBJECT(IGNORED)"),
    ],
    "radio_config": [
        ("interface", "TEXT"), ("ssid", "TEXT"), ("mac", "TEXT"), ("mac_vendor", "TEXT"),
        ("frequency", "TEXT"), ("settings", "OBJECT(IGNORED)"),
    ],
    "nic_counter": [
        ("intf", "TEXT"), ("rx_bytes", "BIGINT"), ("tx_bytes", "BIGINT"),
    ],
    "system": [
        ("uptime_secs", "BIGINT"), ("load_1", "DOUBLE"), ("load_5", "DOUBLE"),
        ("load_15", "DOUBLE"), ("mem_total", "BIGINT"), ("mem_used", "BIGINT"),
        ("mem_free", "BIGINT"), ("mem_shared", "BIGINT"), ("mem_buffers", "BIGINT"),
        ("mem_cached", "BIGINT"), ("cpu_idle_pct", "DOUBLE"),
    ],
    "ip_neighbor": [
        ("ip", "TEXT"), ("family", "TEXT"), ("iface", "TEXT"), ("mac", "TEXT"),
        ("mac_vendor", "TEXT"), ("is_router", "BOOLEAN"), ("state", "TEXT"),
    ],
    "lldp_neighbor": [
        ("interface", "TEXT"), ("rid", "TEXT"), ("chassis_id", "TEXT"),
        ("chassis_id_vendor", "TEXT"), ("sys_name", "TEXT"), ("sys_descr", "TEXT"),
        ("mgmt_ip", "TEXT"), ("port_id", "TEXT"), ("port_id_vendor", "TEXT"),
        ("port_descr", "TEXT"), ("capabilities", "OBJECT(IGNORED)"),
    ],
}


def column_names(table: str) -> list[str]:
    """Ordered data-column names for ``table`` (excludes the id/meta prefix)."""
    return [name for name, _type in TABLES[table]]


def _col_sql(name: str) -> str:
    """Quote ``timestamp`` (a CrateDB reserved word); pass other names through."""
    return '"timestamp"' if name == "timestamp" else name


def create_table_sql(table: str) -> str:
    """``CREATE TABLE IF NOT EXISTS`` for one structured table."""
    cols = PK_PREFIX + tuple(TABLES[table])
    body = ",\n".join(f"    {_col_sql(name)} {ctype}" for name, ctype in cols)
    return f"CREATE TABLE IF NOT EXISTS velop.{table} (\n{body}\n)"


def schema_sql() -> str:
    """Full DDL for all structured tables, ready to apply to CrateDB."""
    header = (
        "-- velop structured-table schema -- GENERATED from velop_watcher/schema.py.\n"
        "-- Regenerate with:  python -m velop_watcher.schema > sql/velop_schema.sql\n"
        "--\n"
        "-- The watcher is Kafka-only; the Connect JDBC sinks land records into these\n"
        "-- tables, which must pre-exist (the sinks run auto.create=false). Apply once,\n"
        "-- e.g.  crash < sql/velop_schema.sql  (or psql, or the CrateDB admin UI).\n\n"
    )
    return header + ";\n\n".join(create_table_sql(t) for t in TABLES) + ";\n"


if __name__ == "__main__":
    print(schema_sql(), end="")
