"""Canonical CrateDB schema for the structured ``velop.*`` tables.

The watcher no longer writes to CrateDB directly. Records flow watcher -> Kafka
(Confluent-Avro) -> Kafka Connect JDBC sinks -> CrateDB, so the tables must
**pre-exist** (the sinks run ``auto.create=false``). This module is the single
source of truth for each table's column order and CrateDB type:

- ``kafka_sink.TABLE_SPECS`` mirrors :data:`TABLES` (asserted in tests), and
- ``sql/velop_schema.sql`` is generated by :func:`schema_sql` (run
  ``python -m velop_watcher.schema`` to regenerate it).

The same table definitions also generate a **PostgreSQL** version of the DDL
(``sql/velop_schema_postgres.sql``, ``python -m velop_watcher.schema
--dialect postgres``) for running the pipeline against stock PostgreSQL instead
of CrateDB: the CrateDB-only types map over (``DOUBLE`` -> ``DOUBLE PRECISION``,
``ARRAY(TEXT)`` -> ``TEXT[]``, ``OBJECT(IGNORED)`` -> ``JSONB``), and because
PostgreSQL does not index every column the way CrateDB does, the postgres DDL
also emits the indexes (:data:`PG_INDEXES`) the ``sql/grafana_*.sql``
views need, plus the ``velop.epoch_ms``/``velop.try_bigint``/``velop.try_double``
helpers that stand in for CrateDB's ``::BIGINT``-on-timestamp cast and
``TRY_CAST``.

``id``/``snapshot_id``/``fetched_at`` are prepended to every table and are not
listed per-table here. Only the 11 structured tables live here; the raw_text
dumps (``sysinfo``/``node_sysinfo``) and the old ``oui`` cache are gone with the
direct-write path.
"""

from __future__ import annotations

# Columns prepended to every structured table, in order.
PK_PREFIX: tuple[tuple[str, str], ...] = (
    ("id", "TEXT PRIMARY KEY"),
    ("snapshot_id", "TEXT"),
    ("fetched_at", "TIMESTAMP WITH TIME ZONE"),
)

# Per-table data columns: ordered (name, CrateDB type). Order must match the
# Avro column order in kafka_sink.TABLE_SPECS (a test asserts this).
TABLES: dict[str, list[tuple[str, str]]] = {
    "device": [
        ("uuid", "TEXT"), ("mac", "TEXT"), ("mac_vendor", "TEXT"), ("ip", "TEXT"),
        ("conn", "TEXT"), ("status", "TEXT"), ("name", "TEXT"), ("friendly_name", "TEXT"),
        ("fw_ver", "TEXT"), ("role", "TEXT"),
        ("extra_macs", "ARRAY(TEXT)"), ("extra_macs_vendor", "ARRAY(TEXT)"),
    ],
    "wlan_client": [
        ("client_mac", "TEXT"), ("client_mac_vendor", "TEXT"), ("stat", "TEXT"),
        ("net", "TEXT"), ("node", "TEXT"), ("mcs", "TEXT"), ("rssi", "INTEGER"),
        ("last_seen", "TEXT"),
    ],
    "backhaul": [
        ("node_mac", "TEXT"), ("node_mac_vendor", "TEXT"), ("node_ip", "TEXT"),
        ("parent_ip", "TEXT"), ("intf", "TEXT"), ("chan", "TEXT"), ("rssi", "TEXT"),
        ("speed", "DOUBLE"), ("state", "TEXT"), ("timestamp", "BIGINT"),
    ],
    "ping": [
        ("target", "TEXT"), ("transmitted", "INTEGER"), ("received", "INTEGER"),
        ("loss_pct", "DOUBLE"), ("rtt_min", "DOUBLE"), ("rtt_avg", "DOUBLE"),
        ("rtt_max", "DOUBLE"),
    ],
    "node": [
        ("uuid", "TEXT"), ("mac", "TEXT"), ("mac_vendor", "TEXT"), ("ip", "TEXT"),
        ("name", "TEXT"), ("role", "TEXT"), ("sku", "TEXT"), ("serial_number", "TEXT"),
        ("fw_ver", "TEXT"), ("mode", "TEXT"), ("model_base", "TEXT"),
        ("model_number", "TEXT"), ("hw_version", "TEXT"),
        ("userap2g_bssid", "TEXT"), ("userap2g_bssid_vendor", "TEXT"), ("userap2g_channel", "TEXT"),
        ("userap5gl_bssid", "TEXT"), ("userap5gl_bssid_vendor", "TEXT"), ("userap5gl_channel", "TEXT"),
        ("userap5gh_bssid", "TEXT"), ("userap5gh_bssid_vendor", "TEXT"), ("userap5gh_channel", "TEXT"),
        ("devinfo", "OBJECT(IGNORED)"),
    ],
    "radio_stats": [
        ("radio", "TEXT"), ("band", "TEXT"), ("source_node_mac", "TEXT"),
        ("source_node_name", "TEXT"), ("source_node_ip", "TEXT"), ("source_role", "TEXT"),
        ("stats", "OBJECT(IGNORED)"),
    ],
    "radio_config": [
        ("interface", "TEXT"), ("ssid", "TEXT"), ("mac", "TEXT"), ("mac_vendor", "TEXT"),
        ("frequency", "TEXT"), ("settings", "OBJECT(IGNORED)"),
    ],
    "nic_counter": [
        ("intf", "TEXT"), ("rx_bytes", "BIGINT"), ("tx_bytes", "BIGINT"),
    ],
    "system": [
        ("uptime_secs", "BIGINT"), ("load_1", "DOUBLE"), ("load_5", "DOUBLE"),
        ("load_15", "DOUBLE"), ("mem_total", "BIGINT"), ("mem_used", "BIGINT"),
        ("mem_free", "BIGINT"), ("mem_shared", "BIGINT"), ("mem_buffers", "BIGINT"),
        ("mem_cached", "BIGINT"), ("cpu_idle_pct", "DOUBLE"),
        ("source_node_mac", "TEXT"), ("source_node_name", "TEXT"),
        ("source_node_ip", "TEXT"), ("source_role", "TEXT"),
    ],
    "ip_neighbor": [
        ("ip", "TEXT"), ("family", "TEXT"), ("iface", "TEXT"), ("mac", "TEXT"),
        ("mac_vendor", "TEXT"), ("is_router", "BOOLEAN"), ("state", "TEXT"),
    ],
    "lldp_neighbor": [
        ("interface", "TEXT"), ("rid", "TEXT"), ("chassis_id", "TEXT"),
        ("chassis_id_vendor", "TEXT"), ("sys_name", "TEXT"), ("sys_descr", "TEXT"),
        ("mgmt_ip", "TEXT"), ("port_id", "TEXT"), ("port_id_vendor", "TEXT"),
        ("port_descr", "TEXT"), ("capabilities", "OBJECT(IGNORED)"),
    ],
}


# ---------------------------------------------------------------------------
# PostgreSQL dialect
# ---------------------------------------------------------------------------

# CrateDB type -> PostgreSQL type. A KeyError here is deliberate: a new CrateDB
# type added to TABLES must be given a postgres equivalent before the postgres
# DDL can be generated (a test asserts every type in TABLES is mapped).
PG_TYPES: dict[str, str] = {
    "TEXT PRIMARY KEY": "TEXT PRIMARY KEY",
    "TEXT": "TEXT",
    "TIMESTAMP WITH TIME ZONE": "TIMESTAMPTZ",
    "INTEGER": "INTEGER",
    "BIGINT": "BIGINT",
    "DOUBLE": "DOUBLE PRECISION",
    "BOOLEAN": "BOOLEAN",
    "ARRAY(TEXT)": "TEXT[]",
    "OBJECT(IGNORED)": "JSONB",
}

# Helper functions the postgres views need, standing in for CrateDB builtins
# that PostgreSQL has no equivalent of:
#   * CrateDB casts a timestamp straight to epoch-ms (``fetched_at::BIGINT``),
#     which the Grafana panels compare against ${__from}/${__to}. In PostgreSQL
#     that cast is an error, so ``velop.epoch_ms(fetched_at)`` does it instead.
#     It is IMMUTABLE, so it can be indexed if a panel ever needs it.
#   * CrateDB has TRY_CAST (NULL instead of raising on bad input), used to pull
#     numbers out of the OBJECT(IGNORED) blobs. ``velop.try_bigint`` /
#     ``velop.try_double`` are the equivalents. They VALIDATE WITH A REGEX rather
#     than catching the cast error: the obvious plpgsql "BEGIN RETURN x::BIGINT;
#     EXCEPTION WHEN others THEN RETURN NULL; END" opens a subtransaction, and a
#     subtransaction is illegal once the executor has entered parallel mode --
#     PostgreSQL aborts the whole query with "cannot start subtransactions
#     during a parallel operation" as soon as it picks a parallel plan for one
#     of the views. Marking them PARALLEL UNSAFE would fix that too, but at the
#     cost of never parallelising the views that use them; the regex form stays
#     PARALLEL SAFE and is faster besides. The length guard keeps an absurdly
#     long digit string from overflowing BIGINT (which would raise, not return
#     NULL).
PG_FUNCTIONS = r"""CREATE OR REPLACE FUNCTION velop.epoch_ms(ts TIMESTAMPTZ) RETURNS BIGINT
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS
$$ SELECT (EXTRACT(EPOCH FROM ts) * 1000)::BIGINT $$;

CREATE OR REPLACE FUNCTION velop.try_bigint(txt TEXT) RETURNS BIGINT
    LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
$$ SELECT CASE
       WHEN txt ~ '^\s*[-+]?[0-9]+\s*$' AND length(btrim(txt)) <= 18
       THEN btrim(txt)::BIGINT
   END $$;

CREATE OR REPLACE FUNCTION velop.try_double(txt TEXT) RETURNS DOUBLE PRECISION
    LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
$$ SELECT CASE
       WHEN txt ~ '^\s*[-+]?([0-9]+\.?[0-9]*|\.[0-9]+)([eE][-+]?[0-9]{1,3})?\s*$'
       THEN btrim(txt)::DOUBLE PRECISION
   END $$;
"""

# Indexes emitted by the postgres DDL only. CrateDB indexes every column by
# default; PostgreSQL does not, and every grafana_*.sql view self-joins a table
# to its own previous snapshot, so without these each view degrades into
# repeated sequential scans as history accumulates.
PG_INDEXES: tuple[tuple[str, tuple[str, ...]], ...] = (
    # every table is filtered/ordered by snapshot time
    *((table, ("fetched_at",)) for table in TABLES),
    # v_device_wlan joins device to wlan_client within one snapshot
    ("device", ("snapshot_id",)),
    ("wlan_client", ("snapshot_id",)),
    # the rate views' self-joins: per-series key, then time
    ("nic_counter", ("intf", "fetched_at")),
    ("radio_stats", ("source_node_mac", "band", "radio", "fetched_at")),
    ("ip_neighbor", ("family", "fetched_at")),
)


def column_names(table: str) -> list[str]:
    """Ordered data-column names for ``table`` (excludes the id/meta prefix)."""
    return [name for name, _type in TABLES[table]]


def _col_sql(name: str) -> str:
    """Quote ``timestamp`` (reserved in both CrateDB and PostgreSQL)."""
    return '"timestamp"' if name == "timestamp" else name


def _type_sql(ctype: str, dialect: str) -> str:
    """Render one column's CrateDB type for ``dialect`` ("crate"/"postgres")."""
    if dialect == "crate":
        return ctype
    if dialect == "postgres":
        return PG_TYPES[ctype]
    raise ValueError(f"unknown dialect: {dialect!r}")


def create_table_sql(table: str, dialect: str = "crate") -> str:
    """``CREATE TABLE IF NOT EXISTS`` for one structured table."""
    cols = PK_PREFIX + tuple(TABLES[table])
    body = ",\n".join(
        f"    {_col_sql(name)} {_type_sql(ctype, dialect)}" for name, ctype in cols
    )
    return f"CREATE TABLE IF NOT EXISTS velop.{table} (\n{body}\n)"


def create_index_sql(table: str, columns: tuple[str, ...]) -> str:
    """``CREATE INDEX IF NOT EXISTS`` for one postgres index (see PG_INDEXES)."""
    name = f"idx_{table}_{'_'.join(columns)}"
    cols = ", ".join(_col_sql(c) for c in columns)
    return f"CREATE INDEX IF NOT EXISTS {name} ON velop.{table} ({cols})"


_CRATE_HEADER = """\
-- velop structured-table schema -- GENERATED from velop_watcher/schema.py.
-- Regenerate with:  python -m velop_watcher.schema > sql/velop_schema.sql
--
-- The watcher is Kafka-only; the Connect JDBC sinks land records into these
-- tables, which must pre-exist (the sinks run auto.create=false). Apply once,
-- e.g.  crash < sql/velop_schema.sql  (or psql, or the CrateDB admin UI).

"""

_PG_HEADER = """\
-- velop structured-table schema, PostgreSQL -- GENERATED from velop_watcher/schema.py.
-- Regenerate with:
--   python -m velop_watcher.schema --dialect postgres > sql/velop_schema_postgres.sql
--
-- A stock-PostgreSQL translation of sql/velop_schema.sql, for running the
-- pipeline against PostgreSQL instead of CrateDB. Same tables, same column
-- order, same id/upsert contract; only the CrateDB-only types change:
--     DOUBLE          -> DOUBLE PRECISION
--     ARRAY(TEXT)     -> TEXT[]    (device.extra_macs / extra_macs_vendor)
--     OBJECT(IGNORED) -> JSONB     (node.devinfo, radio_stats.stats, ...)
--
-- Apply once:  psql -f sql/velop_schema_postgres.sql
-- Then the views:  psql -f sql/grafana_<name>.sql
--
-- ALSO EMITTED HERE (CrateDB needs neither):
--   * velop.epoch_ms()/try_bigint()/try_double() -- stand-ins for CrateDB's
--     fetched_at::BIGINT epoch-ms cast and TRY_CAST, used by the postgres
--     grafana_*.sql views.
--   * indexes -- CrateDB indexes every column by default; PostgreSQL does not,
--     and every rate view self-joins a table to its own previous snapshot.
--
-- CONNECT JDBC SINK NOTES -- the PostgreSQL sinks are connect/*-postgres.json
-- (register them with `./connect/install-sinks.sh --target=postgres`):
--   * They use org.postgresql.Driver and a jdbc:postgresql:// URL, and keep
--     auto.create=false and insert.mode=upsert / pk.fields=id -- on PostgreSQL
--     that becomes a real ON CONFLICT (id) DO UPDATE against the PRIMARY KEY.
--   * The OBJECT(IGNORED)->JSONB columns are produced as JSON *strings* (see
--     kafka_sink), and PostgreSQL will not implicitly coerce TEXT to JSONB on
--     insert. The sink URLs therefore carry ?stringtype=unspecified, which makes
--     the driver send them untyped so the server casts them. Do not drop it.
--   * extra_macs/extra_macs_vendor are real Avro arrays and land natively in
--     TEXT[] -- but ONLY because kafka_sink sends an EMPTY array as null. The
--     JDBC sink binds a non-empty Avro array as a varchar[] parameter and
--     stringifies an empty one to the literal "[]", which PostgreSQL rejects
--     ("malformed array literal"); CrateDB accepts it, so this only ever bit
--     PostgreSQL. Records produced before that fix carry [] and are dropped by
--     the sink's errors.tolerance=all -- see connect/README.md for the
--     ReplaceField backfill workaround.

"""


def schema_sql(dialect: str = "crate") -> str:
    """Full DDL for all structured tables, ready to apply.

    ``dialect="crate"`` reproduces ``sql/velop_schema.sql``; ``"postgres"``
    reproduces ``sql/velop_schema_postgres.sql`` (schema + helper functions +
    tables + indexes).
    """
    tables = ";\n\n".join(create_table_sql(t, dialect) for t in TABLES) + ";\n"
    if dialect == "crate":
        return _CRATE_HEADER + tables
    if dialect != "postgres":
        raise ValueError(f"unknown dialect: {dialect!r}")
    indexes = ";\n".join(create_index_sql(t, cols) for t, cols in PG_INDEXES) + ";\n"
    return (
        _PG_HEADER
        + "CREATE SCHEMA IF NOT EXISTS velop;\n\n"
        + PG_FUNCTIONS
        + "\n"
        + tables
        + "\n"
        + indexes
    )


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--dialect",
        choices=("crate", "postgres"),
        default="crate",
        help="SQL dialect to emit (default: crate)",
    )
    print(schema_sql(ap.parse_args().dialect), end="")
