-- grafana_device_wlan_postgres.sql (PostgreSQL)
--
-- PostgreSQL translation of sql/grafana_device_wlan.sql. No DDL here -- these are
-- flat panel queries, not a view. The only CrateDB-specific SQL is the epoch-ms
-- cast:
--     fetched_at::BIGINT  ->  velop.epoch_ms(fetched_at)
-- velop.epoch_ms() is created by sql/velop_schema_postgres.sql; apply that first.
--
-- Devices joined to their Wi-Fi link stats: one row per device with a display
-- name, IP, MCS rate index and RSSI.
--
-- WHAT THIS SHOWS:
--   velop.device is the router's device table (every known host: wired + Wi-Fi),
--   velop.wlan_client is the per-AP wireless association table (MCS/RSSI only
--   exist for associated Wi-Fi clients). We drive from velop.device (there is
--   always a device row) and LEFT JOIN the Wi-Fi stats on, so:
--     * Wi-Fi clients get their mcs/rssi
--     * wired hosts (and Wi-Fi clients not currently associated) keep their row
--       with mcs/rssi NULL
--   The join is scoped to a single snapshot (d.snapshot_id = w.snapshot_id) so a
--   device is only ever paired with a client from the SAME dump, then matched on
--   MAC (device.mac = wlan_client.client_mac, lowercased to be case-safe).
--
--   `name` falls back: friendly_name (JNAP, full) -> CGI name (capped ~16 chars,
--   often blank) -> the device's OUI vendor -> raw MAC. So every row has a label
--   even when the router never learned a hostname.
--
-- GRAFANA GOTCHA (see CLAUDE.md / sql/grafana_radio_rates_postgres.sql):
--   Grafana's PostgreSQL frame converter silently drops NUMERIC (OID 1700)
--   columns. Nothing here is computed/ROUND()ed: rssi is INTEGER, mcs is TEXT,
--   so both render fine. If you want to graph mcs as a numeric line, cast it
--   explicitly with velop.try_double(w.mcs) (float8/OID 701, and NULL rather
--   than an error on a non-numeric mcs) -- not NUMERIC.
--
-- USAGE:
--   These are flat panel queries (no view). Time series panels want a numeric
--   value per series (rssi graphs cleanly); for the full name/IP/MCS/RSSI view
--   use a Table panel. ${__from}/${__to} render as epoch-ms, matching
--   velop.epoch_ms(fetched_at) exactly (integer vs integer -- no timezone shift).


-- NOTE: every panel query below is COMMENTED OUT on purpose. ${__from} /
-- ${__to} are Grafana macros, not SQL, so an uncommented panel query makes
-- this file fail under `psql -f`. Copy one into a panel and drop the `-- `.
--
-- ===========================================================================
-- Devices + Wi-Fi link stats over the dashboard window (Table panel)
-- ===========================================================================
-- SELECT
--   d.fetched_at                                                AS "time",
--   COALESCE(
--     NULLIF(d.friendly_name, ''),
--     NULLIF(d.name, ''),
--     d.mac_vendor,
--     d.mac
--   )                                                           AS name,
--   d.ip                                                        AS ip,
--   w.mcs                                                       AS mcs,
--   w.rssi                                                      AS rssi
-- FROM velop.device d
-- LEFT JOIN velop.wlan_client w
--        ON d.snapshot_id = w.snapshot_id
--       AND lower(d.mac) = lower(w.client_mac)
-- WHERE velop.epoch_ms(d.fetched_at) BETWEEN ${__from} AND ${__to}
-- ORDER BY "time" ASC, name;


-- ===========================================================================
-- RSSI per device over time (Time series panel; name is the series label)
-- ===========================================================================
-- SELECT
--   d.fetched_at AS "time",
--   COALESCE(NULLIF(d.friendly_name, ''), NULLIF(d.name, ''), d.mac_vendor, d.mac) AS name,
--   w.rssi
-- FROM velop.device d
-- LEFT JOIN velop.wlan_client w
--        ON d.snapshot_id = w.snapshot_id
--       AND lower(d.mac) = lower(w.client_mac)
-- WHERE w.rssi IS NOT NULL
--   AND velop.epoch_ms(d.fetched_at) BETWEEN ${__from} AND ${__to}
-- ORDER BY "time" ASC;


-- ===========================================================================
-- Latest snapshot only (Table panel) -- swap the time-range filter for the
-- newest snapshot within the dashboard window.
-- ===========================================================================
-- SELECT
--   COALESCE(NULLIF(d.friendly_name, ''), NULLIF(d.name, ''), d.mac_vendor, d.mac) AS name,
--   d.ip, w.mcs, w.rssi
-- FROM velop.device d
-- LEFT JOIN velop.wlan_client w
--        ON d.snapshot_id = w.snapshot_id
--       AND lower(d.mac) = lower(w.client_mac)
-- WHERE velop.epoch_ms(d.fetched_at) = (
--         SELECT MAX(velop.epoch_ms(fetched_at)) FROM velop.device
--         WHERE velop.epoch_ms(fetched_at) <= ${__to}
--       )
-- ORDER BY name;


-- ===========================================================================
-- RSSI Distribution (Time series / bar chart: client count per signal band)
-- ===========================================================================
-- CAREFUL -- this one is why the join below is an INNER join, not a LEFT join.
-- w.rssi is NULL for every device that is not a currently-associated Wi-Fi
-- client, and in SQL `NULL >= -50` is NULL, not FALSE. So with a LEFT JOIN
-- every WHEN falls through and `ELSE 'Poor'` silently swallows the lot: over a
-- 6-hour window that produced 4,742 "Poor" readings of which only 24 were real
-- weak signals -- a confident, plausible, completely wrong panel that never
-- raises an error. Join inner so ELSE only ever sees genuine weak signal.
--
-- To show the non-Wi-Fi devices as their own category instead, switch back to a
-- LEFT JOIN and make `WHEN w.rssi IS NULL THEN 'Not on Wi-Fi'` the FIRST branch.
-- SELECT d.fetched_at AS "time",
--        CASE
--          WHEN w.rssi >= -50 THEN 'Excellent'
--          WHEN w.rssi >= -60 THEN 'Very good'
--          WHEN w.rssi >= -67 THEN 'Good'
--          WHEN w.rssi >= -70 THEN 'Marginal'
--          ELSE 'Poor'
--        END      AS rssi_band,
--        count(*) AS rssi_count
-- FROM velop.device d
-- JOIN velop.wlan_client w
--   ON w.snapshot_id = d.snapshot_id
--  AND lower(w.client_mac) = lower(d.mac)
-- WHERE velop.epoch_ms(d.fetched_at) BETWEEN ${__from} AND ${__to}
-- GROUP BY d.fetched_at, rssi_band
-- ORDER BY "time" ASC, rssi_band;


-- ===========================================================================
-- RSSI for one device ($ip template variable)
-- ===========================================================================
-- The lower() on BOTH sides is load-bearing: wlan_client.client_mac is always
-- lowercase, but device.mac is mixed (564 of 39,150 rows uppercase over a
-- two-day sample, e.g. D8:EC:5E:8E:ED:9E). A bare MAC equality happens to work
-- while every associated client has a lowercase MAC, then silently returns an
-- empty graph the day one does not.
--
-- '$ip' assumes a single-value variable. For multi-value or "All", drop the
-- quotes and use IN (${ip:sqlstring}).
-- SELECT wc.fetched_at, wc.client_mac, wc.rssi
-- FROM velop.wlan_client wc
-- WHERE lower(wc.client_mac) IN (
--         SELECT DISTINCT lower(mac) FROM velop.device WHERE ip = '$ip'
--       )
--   AND velop.epoch_ms(wc.fetched_at) BETWEEN ${__from} AND ${__to}
-- ORDER BY wc.fetched_at;
